### ISSUE TITLE
rpm.copyTo is unable to copy the generated rpm to different location 

### ISSUE THREAD

**Issue by Emran80** [mojohaus/rpm-maven-plugin#111]
I am using the rpm:rpm goal configured in pom, and when i use copy to option in pom or command line its failing . using command mvn clean package -Drpm.copyTo="/path...".

**Comment by Emran80** [comment]
After modifying the code to print more log I realized it was expecting a destination file path instead of directory location.
I was specifying a directory location for copyTo and it was expecting a destination file path.

**Comment by gunslingor** [comment]
Could you post an example on how to use this undocumented feature?

I am trying to copy the resulting RPM from buried in /target/rpm/project_name/RPMS/noarch to /target

<copyTo>target</copyTo> --> Fails
<copyTo>target/test</copyTo> --> works but renames the file to test, like you indicate.

Since the resulting RPM ID (which is dynamically assigned when using SNAPSHOT) is unknown, there is no way to copy it without renaming it blindly? Why is this called copyTo... shouldn't it be copyToAndForcedRename?
