### ISSUE TITLE
Is it possible to use redline to build RPM

### ISSUE THREAD

**Issue by gembin** [mojohaus/rpm-maven-plugin#31]
Is it possible to use https://github.com/craigwblake/redline, Pure Java RPM Library, in case the OS don't have `rpm` command ?

**Comment by dantran** [comment]
yes, waiting for some one icky enough to implement. It is not small thou

**Comment by rickard-von-essen** [comment]
I think using a Java implementation of rpm is not that useful as it first seams. RPM is very dependent on the configuration and macros etc on the build machine and you should build your rpm's on a server with the same OS and version as the target system.

The simple solution to all this is to use [vagarant](https://vagantup.com).

**Comment by gembin** [comment]
In my opinion,  a common use case of  this maven plugin is packaging java application as a RPM, it's often no need to build/make the source as rpmbuild tool does, is this correct?

Otherwise, i would prefer just using rpmbuild tool with a spec file which would be more straightforward.

**Comment by rickard-von-essen** [comment]
There are some details that you get when using ```rpmbuild```some macro defs for example where your docs should be installed. If you don't use macros that won't be a problem. More importantly the configuration gives you the correct compression algoritm. If I remember correctly a rpm build on CentOS 6 doesn't install on CentOS 5 because they changed the compression algorithm. 

So to summarise it would be fine to build with a java lib on say Windows but it would require that you stick to a strict subset of rpm and that you know and define some additional details that you otherwise can be ignorant of, such as compression algorithm.

**Comment by leif81** [comment]
FWIW, using Cygwin is a pretty effective way to build RPM's for Java projects using this plugin.

See http://stackoverflow.com/a/40811390/52176

**Comment by dantran** [comment]
close as wont fix
